-- ~/.config/nvim/lua/core/colorscheme.lua
-- NOTE: theme setup is now handled entirely by plugins/ui/theme-loader.lua
-- (which calls core.theme.setup() in its plugin config block).
-- This file is kept for compatibility but does nothing at startup.
-- You can safely delete it if nothing else requires it.
